repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.2.0
  hooks:
  - id: add-trailing-comma
- repo: https://github.com/lk16/detect-missing-init
  rev: v0.1.6
  hooks:
  - id: detect-missing-init
    args: ['--create', "--track", "--python-folders", "backend/src/prontia"]
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.17.0
  hooks:
  - id: markdownlint-cli2
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
  - id: mypy
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.1
  hooks:
  - id: ruff-check
    args: [ --fix ]
  - id: ruff-format
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.8.19
  hooks:
  - id: uv-lock
